server:
  port: 8080
logging:
  level:
    #项目日志级别
    com.tc.security: debug
    #spring日志级别
    org.springframework: info
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/security00
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: mapper/*.xml
  type-aliases-package: com.tc.security.pojo
